
#include <time.h>
#include <iostream>
#include <iomanip>
using namespace std;

struct Node
{
	int n;
	Node* next = NULL;
	Node(int num) : n(num) {};
};

void append(Node** head_ref, int new_data, bool b)
{
	clock_t start = clock();

	/* 1. allocate node */
	Node* new_node = new Node(new_data);

	Node* last = *head_ref; /* used in step 5*/

	/* 3. This new node is going to be
	the last node, so make next of
	it as NULL*/
	new_node->next = NULL;

	/* 4. If the Linked List is empty,
	then make the new node as head */
	if (*head_ref == NULL)
	{
		*head_ref = new_node;
		return;
	}

	/* 5. Else traverse till the last node */
	while (last->next != NULL)
	{
		last = last->next;
	}

	/* 6. Change the next of last node */
	last->next = new_node;

	clock_t ends = clock();
	double time_taken = ((double)ends - start) / CLOCKS_PER_SEC;
	if (b)
		cout << "Duration with two *: " << time_taken << endl;

	return;
}

void append2(Node* head, int data, bool b)
{
	clock_t start = clock();

	Node* newNode = new Node(data);
	while (head->next != NULL)
		head = head->next;

	head->next = newNode;

	clock_t ends = clock();
	double time_taken = ((double)ends - start) / CLOCKS_PER_SEC;
	if (b)
		cout << "Duration with one *: " << time_taken << endl;

}


int main()
{
	Node* head = new Node(5);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false); append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);
	append(&head, 2, false);

	Node* secondHead = new Node(7);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false); append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);
	append2(secondHead, 4, false);


	append(&head, 5, true);
	append2(head, 6, true);
	return 0;
}

